language: generic
sudo: false
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis
  - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-26-pretest-travis
    - env: EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
install:
  - make deps
script:
  - emacs --version
  - make check
notifications:
email: false
